<a href="https://colab.research.google.com/github/Aliyan167/AI_18/blob/main/lab_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 1D array of numbers from 0 to 9
array = np.arange(10)

print(array)




[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# Create a 1D array of numbers from 1 to 9
array_1d = np.arange(1, 10)

# Reshape the 1D array into a 2D array with shape (3, 3)
array_2d = array_1d.reshape(3, 3)

print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100
array_3d = np.random.randint(1, 101, size=(2, 3, 4))

print(array_3d)

[[[72 55 77 13]
  [14 52 47 35]
  [43 79 24 66]]

 [[13 51 72  2]
  [58 58 36 26]
  [59 71 69 18]]]
