<a href="https://colab.research.google.com/github/Aliyan167/AI_18/blob/main/lab_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 1D array of numbers from 0 to 9
array = np.arange(10)

print(array)




[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# Create a 1D array of numbers from 1 to 9
array_1d = np.arange(1, 10)

# Reshape the 1D array into a 2D array with shape (3, 3)
array_2d = array_1d.reshape(3, 3)

print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100
array_3d = np.random.randint(1, 101, size=(2, 3, 4))

print(array_3d)

[[[72 55 77 13]
  [14 52 47 35]
  [43 79 24 66]]

 [[13 51 72  2]
  [58 58 36 26]
  [59 71 69 18]]]


In [7]:
import numpy as np

# Sample 2D array (arr2)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Extracting the second row
second_row = arr2[1]
print("Second row of arr2:", second_row)


Second row of arr2: [4 5 6]


In [8]:
import numpy as np

# Sample 2D array (arr2)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Extracting the element at the 3rd row and 2nd column
element = arr2[2, 1]
print("Element at 3rd row and 2nd column of arr2:", element)


Element at 3rd row and 2nd column of arr2: 8


In [9]:
import numpy as np

# Sample 3D array (arr3)
arr3 = np.array([[[1, 2, 3],
                   [4, 5, 6]],

                  [[7, 8, 9],
                   [10, 11, 12]],

                  [[13, 14, 15],
                   [16, 17, 18]]])

# Extracting all elements from the 0th layer
first_layer = arr3[0]
print("All elements from the 0th layer of arr3:\n", first_layer)


All elements from the 0th layer of arr3:
 [[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np

# Sample 1D array with 10 elements
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Reshaping the 1D array into a 2x5 2D array
reshaped_array = arr1.reshape(2, 5)
print("Reshaped 2D array (2x5):\n", reshaped_array)


Reshaped 2D array (2x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
